apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-repo-2
  labels:
    app: example-repo-2
    backstage.io/kubernetes-id: example-repo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-repo-2
  template:
    metadata:
      labels:
        app: example-repo-2
        backstage.io/kubernetes-id: example-repo-2
    spec:
      containers:
        - name: example-repo-2
          image: backstageadmin/example-repo-2:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


