apiVersion: v1
kind: Service
metadata:
  name: example-repo-2
spec:
  type: NodePort
  selector:
    app: example-repo-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30017   # You can change this (range: 30000–32767)
      
# apiVersion: v1
# kind: Service
# metadata:
#   name: example-repo-2
# spec:
#   selector:
#     app: example-repo-2
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000

#   type: LoadBalancer

